#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#define LOG_CONF_LEVEL_MAIN LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_RPL LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_TCPIP LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_IPV6 LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_6LOWPAN LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_MAC LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_FRAMER LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_ROUTING LOG_LEVEL_NONE

#define TSCH_LOG_CONF_PER_SLOT 1

#define SEND_DRIFT_CALLBACK 1

#define CLOCK_DRIFT_MONITOR 1

#define UIP_CONF_BUFFER_SIZE 200
#define SICSLOWPAN_CONF_FRAG 0


#define CLOCK_CONF_SECOND 128 // gerçek zamanlı olması için, 1 saniyeye 128 tick

#endif /* PROJECT_CONF_H_ */