CONTIKI_PROJECT = node-min
all: $(CONTIKI_PROJECT)

# Make variables
CONTIKI = ../..

MAKE_MAC = MAKE_MAC_TSCH

# Modules needed
MODULES += os/net/app-layer/coap
MODULES += os/services/simple-udp

# Include the main Contiki makefile
include $(CONTIKI)/Makefile.include